version: "3.9"
services:
  xammp:
    image: tomsik68/xampp:8
    volumes:
      - ./exiadrink/www:/www/exiadrink/www 
      - ./exiadrink/logs:/www/exiadrink/logs
      - ./exiadiscount/www:/www/exiadiscount/www 
      - ./exiadiscount/logs:/www/exiadiscount/logs 
      - ./exiadiscount/users:/www/exiadiscount/users
      - ./apache_conf/apache.docker.conf:/opt/lampp/apache2/conf.d/exia.conf
    ports:
      - "22:22"
      - "80:80"